language: android
sudo: required

services:
  - docker

android:
  components:
    - build-tools-27.0.3
    - android-27

script:
  - ./gradlew buildDebug
  - ./gradlew dokka
  - ./gradlew ktlint
  - ./build-words-docker.sh
